title: Adam Young
tagline: iOS Engineer
description: iOS Engineer based in Oakham, UK. Personal site, projects, and writing.
url: https://adam-young.co.uk
lang: en_GB

author:
  name: Adam Young
  email: me@adam-young.co.uk
  url: https://adam-young.co.uk
  twitter: adamayoung

email: me@adam-young.co.uk

github_username: adamayoung
linkedin_username: adamayoung

twitter:
  username: adamayoung
  card: summary_large_image

social:
  name: Adam Young
  links:
    - https://github.com/adamayoung
    - https://www.linkedin.com/in/adamayoung

logo: /assets/images/me.jpg

google_analytics_id: G-ETGHS44KVE

permalink: /blog/:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      image:
        path: /assets/images/me.jpg
        width: 1752
        height: 1763
        alt: Adam Young
  - scope:
      path: ""
      type: posts
    values:
      layout: post

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules

sass:
  style: compressed
